### ISSUE TITLE
Bold italics

### ISSUE THREAD

**Issue by alexcarpenter** [nickbytes/nickbytes.github.io#1]
Include 700 weight italic from web font to get the italic version for intro.

`https://fonts.googleapis.com/css?family=Roboto:400,700,700italic,400italic`

![screen shot on 2015-10-13 at 09-20-18](https://cloud.githubusercontent.com/assets/825855/10455837/b7791486-718b-11e5-912d-0b69a35dc20d.png)

**Comment by nickbytes** [comment]
@alexcarpenter http://sendbytes.space/#/final/1/aGVscGluZyB3aXRoIHRoZSBmb250IHNuYWZ1Lg==/Tmljaw==

I probably do this on all of my sites accidentally. (Including sendbytes.space)
